name = "cosmodiva-worker"
main = "src/index.js"
compatibility_date = "2025-09-25"

[[r2_buckets]]
binding = "COSMO_BUCKET"
bucket_name = "cosmo-content"

[vars]
# Your public site URL (the domain users visit)
SITE_URL = "https://blog.cosmodiva.com"

# IMPORTANT: this must be the PAGES DOMAIN (pages.dev), not a worker URL,
# because the Worker fetches index.html from Pages to inject meta
PAGES_ORIGIN = "https://cosmodivablog.pages.dev"

[observability.logs]
enabled = true