name = "cosmodiva-worker"
main = "src/index.ts"
compatibility_date = "2025-09-25"
compatibility_flags = ["nodejs_compat"]

# Bind to R2 bucket
[[r2_buckets]]
binding = "COSMO_BUCKET"
bucket_name = "cosmo-content"

[[d1_databases]]
binding = "DB"                       # Must match your code (c.env.DB)
database_name = "email-subscribers-db"
database_id = "f5e137db-73ed-4d8a-abdd-a7daa57d5132"  # from `wrangler d1 list`

# Environment variables
[vars]
SITE_URL = "https://blog.cosmodiva.com"
PAGES_ORIGIN = "https://cosmodiva-blog.pages.dev"
