name = "cosmodiva-worker"
main = "src/index.js"
compatibility_date = "2025-09-25"
compatibility_flags = ["nodejs_compat"]

# Bind to R2 bucket
[[r2_buckets]]
binding = "COSMO_BUCKET"
bucket_name = "cosmo-content"

# Environment variables
[vars]
SITE_URL = "https://blog.cosmodiva.com"
PAGES_ORIGIN = "https://cosmodiva-blog.pages.dev"
